### ISSUE TITLE
serializer.data 접근 시 발생하는 TypeError

### ISSUE THREAD

**Issue by tictactoeid** [wafflestudio/rookies#210]
```POST /api/v1/seminar/```를 구현하고 있습니다.
Response의 body에  ```serializer.data```가 들어가게 되는데, 여기서 다음과 같은 오류가 발생합니다.
```TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'```

이 오류가 왜 발생하는 것인지, 해결방법이 무엇인지 모르겠습니다.

저는 seminar/serializers.py에
```InstructorProfileSerializer, ParticipantProfileSerializer, SeminarSerializer Class```를 각각 구현하였고, 
```SeminarSerializer``` 안에 ```Python
instructors = InstructorProfileSerializer(many=True, required=False)
participants = ParticipantProfileSerializer(many=True, required=False)```를 포함시켜 주어진 형태의 Response body를 구성하고자 했습니다.

그리고, ```views.py```의 ```create()```에서
```Python
serializer.save(**serializer.validated_data, instructors = InstructorProfileSerializer(user.instructor))
        return Response(serializer.data, status = status.HTTP_201_CREATED)```
를 통해 serializer를 저장하고, seminar를 생성하고자 했습니다.

이때, Response의 body를 비우면 ```201 Created```가 잘 나타납니다.

**Comment by davin111** [comment]
SeminarSerializer 안을 어떻게 구현하신 것인지 더 구체적으로 설명해주실 수 있을까요?(본문의 줄나눔도 이상한 거 같습니다ㅜ) 단순한 TypeError인 것으로 보아 어딘가 내부적인 잘못이 있어보입니다. stacktrace(에러가 어디서 발생했는지 표시해주는 것)이 콘솔에 있을텐데 잘 살펴보세요. 그리고 전반적으로 드리고 싶은 팁은, 처음부터 많은 것을 구현하여 실행시켜보기보다, 아주 조금씩 정상 동작하는 것을 확인하며 살을 붙여나가세요. 개발에 있어 가장 효율적인 자세라고 생각합니다.

일단 serializer.save()에서 instructors의 값으로 InstructorProfileSerializer 객체 자체를 넣어주는 부분이 매우 어색하게 느껴지네요!

**Comment by tictactoeid** [comment]
```Python
class SeminarSerializer(serializers.ModelSerializer):
    instructors = InstructorProfileSerializer(many=True, required=False)
    participants = ParticipantProfileSerializer(many=True, required=False)


    def create(self, validated_data, **inst):
        if inst:
            validated_data['instructors'] = inst
        return Seminar(validated_data)
```
중요한 부분은 여기일 것 같네요. 현재 이렇게 구성되어 있습니다.
https://kimdoky.github.io/django/2018/07/11/drf-Serializers/
여기를 참고했습니다.

**Comment by tictactoeid** [comment]
아 저 Python은 실제 코드에 있는 것은 아니고, 코드가 highlight되게 하려다가 저렇게 된 것 같습니다.

**Comment by tictactoeid** [comment]
오류 메시지 전문도 첨부하자면
```
Internal Server Error: /api/v1/seminar/
Traceback (most recent call last):
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/onedrive/Git/waffle-rookies-18.5-backend-2/waffle_backend/seminar/views.py", line 52, in create
    return Response(serializer.data, status = status.HTTP_201_CREATED)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/jungjimin/anaconda3/envs/waffleBackend/lib/python3.8/site-packages/rest_framework/fields.py", line 994, in to_representation
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
[28/Sep/2020 14:41:58] "POST /api/v1/seminar/ HTTP/1.1" 500 124123
```
이렇습니다. 이것만 보고 제가 오류 원인을 정확히 파악하기 어려워 질문드렸습니다.

**Comment by davin111** [comment]
Serializer 바로 아래에 attribute로 정의되는 instructors, participants 같은 것들은 field여야 합니다. 이 경우 serializers.SerializerMethodField() 같은 것이 되어야 합니다. 과제 1 이후로 다뤄진 SurveyResultSerializer와 OperatingSystemSerializer의 관계를 살펴보세요. 기존에 #162 등 여러 이슈를 먼저 정독해보시는 것을 권장드립니다.

**Comment by tictactoeid** [comment]
Response의 주어진 body 형태를 구현하는 데 어려움을 겪고 있네요.. 우선 field로 정의해야 한다는 것은 알겠습니다. 조금 더 찾아보겠습니다. 감사합니다.

**Comment by davin111** [comment]
네 그리고, 카카오톡 단톡방에서도 몇 번 말씀드렸듯이, model의 생성이나 수정(write)을 반드시 serializer를 이용해 구현할 필요는 없습니다.

**Comment by tictactoeid** [comment]
사실 그렇게도 구현해 봤는데, 구현 자체는 성공하는데 return에서 똑같이 문제가 발생했습니다. response body 형식을 지켜야 하므로 결국 문제를 해결해야 할 것 같습니다.

**Comment by davin111** [comment]
아마 그러면 serializer에서 read할 때 nested 구조(serializer 안에서 또 다른 serializer를 이용해 data를 serialize 시키기)를 어떻게 처리할 것인지에 대한 고민이 되는 듯한데, 기존 뼈대 코드와 다른 이슈들에서 힌트를 얻으실 수 있을 것이라 생각합니다. 이런 키워드로 구글링 해보셔도 좋구요!

**Comment by tictactoeid** [comment]
예 제가 고민하는 부분이 그 부분입니다. 관련 이슈 한 번 살펴보겠습니다!
