### ISSUE TITLE
mysqlclient 가 설치가 안됩니다

### ISSUE THREAD

**Issue by guzus** [wafflestudio/rookies#77]
구글링해서 이것저것 시도해봤는데 가상환경에 다른것들은 설치가 잘 되었는데 mysqlclient가 설치가 안되네요ㅠㅠ
Mac 쓰고있고, pip install mysqlclient==2.0.1 했을 때  ERROR: Command errored out with exit status 1: 라는 에러메시지가 뜨네요.

해결방법 아시는 분 계신가요?
(라벨링이 지금 안돼서 되는대로 라벨링은 하겠습니다)

**Comment by eldpswp99** [comment]
brew install mysql-connector-c

이 커맨드 입력후에 다시한번 시도해보시겠어요?

**Comment by guzus** [comment]
> `brew install mysql-connector-c`
> 
> 이 커맨드 입력후에 다시한번 시도해보시겠어요?

으악 그래도 안되네요ㅠㅠ
에러메시지는 정확하게는 아래와 같아요ㅠㅠ 감사합니다

    ERROR: Command errored out with exit status 1:
     command: /Users/myunggujung/opt/anaconda3/envs/backend_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-install-lhw9zi6r/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-install-lhw9zi6r/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-pip-egg-info-je_fatyh
         cwd: /private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-install-lhw9zi6r/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-install-lhw9zi6r/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-install-lhw9zi6r/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/f4/2cyn_x9j2558rslmv96ktfw00000gn/T/pip-install-lhw9zi6r/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by dodo4114** [comment]
Mysql도 가상환경에 설치를 해야하나요?
서버라면 몰라도 Db까지 굳이 가상환경에 설치할 필요까진 없을 것 같습니다ㅠ

**Comment by eldpswp99** [comment]
mysqlclient가 python이랑 mysql이랑 연결하는거여서 설치가 필요해 보입니다. requirements에도 있구요

**Comment by eldpswp99** [comment]
여기서 말씀하시는건 mysqlclient 여서 설치가 필요해보입니다. 찾아보니 mysql이랑 python을 연결하는 툴역할을 하는듯 싶네요

**Comment by dodo4114** [comment]
아 sql이 아니라 client 말씀하시는거였군요 ㅠ

**Comment by eldpswp99** [comment]
현재 mysql이 설치되어있는 상황인가요? 아니라면 설치 후 다시 시도해보세요.

**Comment by guzus** [comment]
> 현재 mysql이 설치되어있는 상황인가요? 아니라면 mysql설치 후 다시 시도해보세요.

감사합니다!! 덕분에 mysqlclient 설치했어요. 
알고보니 mysql 설치가 안되어 있었네요ㅠㅠ 분명 설치한줄 알았는데 아니었어요..
https://velog.io/@max9106/mac에-MySQL-설치하기-4ck17gzjk3 저는 이거보고 mysql 설치했어요.
